### PR TITLE
add catch JQStore_JobNotFoundException exception to detectHungJobs, c…

### PR DESCRIPTION
**Pull request by woofyman99**
…ontinue

---
This change is [Reviewable](https://reviewable.io/reviews/apinstein/jqjobs/33)

### CODE REVIEW

**Comment by apinstein** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/JQJobs/JQStore/Propel.php, line 98 \[r1\]](https://reviewable.io:443/reviews/apinstein/jqjobs/33#-KMdge3SDbnEVJ5c7hGM:-KMdge3SDbnEVJ5c7hGN:1867761104) ([raw file](https://github.com/apinstein/jqjobs/blob/57fd81eb9bfc1e5c695385933d82d63a760594ba/src/JQJobs/JQStore/Propel.php#L98)):*
> ```PHP
>         $c->add($this->options['jobMaxRuntimeSecondsColName'], NULL, Criteria::ISNOTNULL);
>         $c->add($this->options['jobMaxRuntimeSecondsColName'], "{$this->options['jobStartDtsColName']} + ({$this->options['jobMaxRuntimeSecondsColName']}||' seconds')::interval < now()", Criteria::CUSTOM);
>         $possiblyHungJobs = call_user_func(array("{$this->propelClassName}Peer", 'doSelect'), $c, $this->con);
> ```

I think if you hack in, for testing purposes, a "delete all jobs from db" at this point, you'll get to test your code below in the actual situation...

---

*[src/JQJobs/JQStore/Propel.php, line 118 \[r1\]](https://reviewable.io:443/reviews/apinstein/jqjobs/33#-KMdgoWzxhHGiFZJnMxT:-KMdgoWzxhHGiFZJnMxU:-1112772727) ([raw file](https://github.com/apinstein/jqjobs/blob/57fd81eb9bfc1e5c695385933d82d63a760594ba/src/JQJobs/JQStore/Propel.php#L118)):*
> ```PHP
>             } catch(JQStore_JobNotFoundException $e) {
>                 // the job already finished, continue the loop
>                 continue;
> ```

do you need to abort the tx? make sure you test that if you have 10 jobs, and there are more in the loop after experiencing the notfound, that the next iterations still work. i would be concerned that the `$con` might be borked b/c the "begin" and "abort/commit" aren't matched...

also I wonder if you would want to PRINT something in this catch to eval whether it's working in prod (at least temporarily)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apinstein/jqjobs/33)*

**Comment by woofyman99** [comment]
*[src/JQJobs/JQStore/Propel.php, line 98 \[r1\]](https://reviewable.io:443/reviews/apinstein/jqjobs/33#-KMdge3SDbnEVJ5c7hGM:-KMdrgvSQLGAfxgibroA:-413381413) ([raw file](https://github.com/apinstein/jqjobs/blob/57fd81eb9bfc1e5c695385933d82d63a760594ba/src/JQJobs/JQStore/Propel.php#L98)):*
<details><summary><i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>
> I think if you hack in, for testing purposes, a "delete all jobs from db" at this point, you'll get to test your code below in the actual situation...
</details>
Yes, that worked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apinstein/jqjobs/33)*

**Comment by woofyman99** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/JQJobs/JQStore/Propel.php, line 118 \[r1\]](https://reviewable.io:443/reviews/apinstein/jqjobs/33#-KMdgoWzxhHGiFZJnMxT:-KMdlvFKzKZwLnp8p2FK:-499146009) ([raw file](https://github.com/apinstein/jqjobs/blob/57fd81eb9bfc1e5c695385933d82d63a760594ba/src/JQJobs/JQStore/Propel.php#L118)):*
<details><summary><i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>
> do you need to abort the tx? make sure you test that if you have 10 jobs, and there are more in the loop after experiencing the notfound, that the next iterations still work. i would be concerned that the `$con` might be borked b/c the "begin" and "abort/commit" aren't matched...
> 
> also I wonder if you would want to PRINT something in this catch to eval whether it's working in prod (at least temporarily)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apinstein/jqjobs/33)*

**Comment by woofyman99** [comment]
ready for review

**Comment by apinstein** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/apinstein/jqjobs/33#-:-KMdyo686IaIwy1bLSau:1417088721)*

**Comment by apinstein** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/JQJobs/JQStore/Propel.php, line 114 \[r2\]](https://reviewable.io:443/reviews/apinstein/jqjobs/33#-KMdyrzO1ZR9BzVovF7g:-KMdyrzO1ZR9BzVovF7h:111543030) ([raw file](https://github.com/apinstein/jqjobs/blob/6973067515a51ae30a2cf0a0e9b4e1e66d584bee/src/JQJobs/JQStore/Propel.php#L114)):*
> ```PHP
>                 $this->con->commit();
>             } catch(JQStore_JobNotFoundException $e) {
>                 // the job already finished, continue the loop
> ```

actually will you note that this is specifically to be graceful in the "race condition of job was overdue but finished by the time we got to it in the loop" -- I fear that if we have to debug in future that "job already finished" won't be clear enough to remember what this solves

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/apinstein/jqjobs/33)*

**Pull request merged**
